### ISSUE TITLE
Exception when binding to Http and Websockets

### ISSUE THREAD

**Issue by ckozak** [lihaoyi/SprayWebSockets#13]
My application needs to provide both Rest API and websockets support. So for that I'm binding to 2 ports at the same time (Spray 1.2):

IO(Http) ! Http.Bind(serviceActor, "0.0.0.0", port = 38080)
IO(Sockets) ! Http.Bind(websocketActor, "0.0.0.0", port = 38081)

but I get an exception that actor name IO-HTTP is already taken.

Exception in thread "main" akka.actor.InvalidActorNameException: actor name [IO-HTTP] is not unique!
    at akka.actor.dungeon.ChildrenContainer$NormalChildrenContainer.reserve(ChildrenContainer.scala:130)
    at akka.actor.dungeon.Children$class.reserveChild(Children.scala:77)
    at akka.actor.ActorCell.reserveChild(ActorCell.scala:338)
    at akka.actor.dungeon.Children$class.makeChild(Children.scala:186)
    at akka.actor.dungeon.Children$class.attachChild(Children.scala:42)
    at akka.actor.ActorCell.attachChild(ActorCell.scala:338)
    at akka.actor.ActorSystemImpl.actorOf(ActorSystem.scala:518)
    at spray.can.HttpExt.<init>(Http.scala:152)
    at spray.can.server.websockets.SocketExt.<init>(Sockets.scala:110)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
    at akka.actor.ReflectiveDynamicAccess$$anonfun$createInstanceFor$2.apply(DynamicAccess.scala:78)
    at scala.util.Try$.apply(Try.scala:161)
    at akka.actor.ReflectiveDynamicAccess.createInstanceFor(DynamicAccess.scala:73)
    at akka.actor.ExtensionKey.createExtension(Extension.scala:153)
    at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:654)
    at akka.actor.ExtensionId$class.apply(Extension.scala:79)
    at akka.actor.ExtensionKey.apply(Extension.scala:149)
    at akka.io.IO$.apply(IO.scala:36)
    at my.Boot.startup(Boot.scala:29)

It works fine if I try to bind only to one server, whether it's HTTP or Sockets and works fine if I bind using different ActorSystems:

IO(Http) ! Http.Bind(serviceActor, MaierConfig.rest.host, port = MaierConfig.rest.port)
IO(Sockets)(ActorSystem()) ! Http.Bind(websocketActor, MaierConfig.websocket.host, port = MaierConfig.websocket.port)

It looks like the problem is in class spray.can.server.websockets.SocketExt, which extends HttpExt which creates a manager actor and sets a hardcoded name to it - "IO-HTTP". Sockets class then cannot initialize because super initialization is called and name IO-HTTP is not unique. Is there a way to avoid this?

**Comment by troypayne** [comment]
+1

**Comment by lihaoyi** [comment]
This probably depends on  https://github.com/lihaoyi/SprayWebSockets/issues/14 being solved first =P Even though I wrote all this stuff and profiled and optimized and all that, I honestly don't remember enough about the code to make intelligent discussion about it, so I won't be much help...

**Comment by troypayne** [comment]
@lihaoyi do any of the pending bug fixes fix this issue?

**Comment by lihaoyi** [comment]
Not sure =P I have forgotten most of the code, so you'll have to patch them down and take a look yourself.

**Comment by troypayne** [comment]
@ckozak, @lihaoyi  perhaps we can look at it together. I desperately need the actors in the same ActorSystem so a solution that once worked before, no longer works for me.

Here's my guess. SocketExt isn't being used/called thus never overriding the manager to create a new name.

Can anyone think of a reason why that would happen?

**Comment by lihaoyi** [comment]
I have no idea what's going on, but one thought is maybe try C&Ping the body of `HttpExt` rather than inheriting from it in `SocketExt`? Maybe there's some weird initialization thing going on when inheriting, but the string `"IO-HTTP"` only exists in `HttpExt`, so hopefully if we don't use it at all it won't magically appear as an actor name

**Comment by troypayne** [comment]
I tried that, but got some compile errors around missing Settings and
Config param

**Comment by lihaoyi** [comment]
What kind of compile errors? `Config`  just sounds like a missing import, and `Settings` sounds like you didn't C&P properly. I mean, if 

``` scala
class HttpExt(system: ExtendedActorSystem) extends akka.io.IO.Extension {
```

compiles, I don't see any reason why a similar `SocketExt` with identical contents shouldn't...

Sorry for all the hand waving, I don't have time to check out the code an debug it, but hopefully I'm still of some help
